### ISSUE TITLE
Add pieces to the pure algebraic pv

### ISSUE THREAD

**Issue by v11580** [maksimKorzh/wukongJS#11]
I want to start working on code that adds the functionality of converting the pure algebraic pv output to descriptive notation. This would, for example, change g1f3 to Ng1f3 and finally to Nf3.

We need to do the following. Any help with items 1 and 2 is appreciated.

1. Identify where in the Wukong code we can declare a variable for each moved piece.
2. Identify where in the code we can introduce this variable to each node output in the pv.
3. draft potential code to implement the idea
4. debug and finalize the solution.

**Comment by v11580** [comment]
According to the documentation for chess.js, we should be able to retrieve the move notation like this:

chess.move('Nge7', { sloppy: true })
// -> { color: 'b', from: 'g8', to: 'e7', flags: 'n', piece: 'n', san: 'Ne7' }  https://github.com/jhlywa/chess.js/

I tried a for each loop for the pv as an array of moves
ARR = pvstring

ARR.forEach((item, index) => {
     game.move(item, { sloppy: true })
     return   console.log(item.san)
})

It returned  "undefined"

**Comment by JavlonMardonov** [comment]
> According to the documentation for chess.js, we should be able to retrieve the move notation like this:
> 
> chess.move('Nge7', { sloppy: true }) // -> { color: 'b', from: 'g8', to: 'e7', flags: 'n', piece: 'n', san: 'Ne7' } https://github.com/jhlywa/chess.js/
> 
> I tried a for each loop for the pv as an array of moves ARR = pvstring
> 
> ARR.forEach((item, index) => { game.move(item, { sloppy: true }) return console.log(item.san) })
> 
> It returned "undefined"

After this, how did you do that? How convert? Is that possible?
