### ISSUE TITLE
Send uciok

### ISSUE THREAD

**Issue by fsmosca** [maksimKorzh/wukongJS#2]
Send uciok message at the end, after receiving uci command and sending the engine info etc.

**Comment by maksimKorzh** [comment]
Oh.. just forgot, sure, I'll fix it. Btw new version is coming soon.
Stay tuned: https://www.youtube.com/channel/UCB9-prLkPwgvlKKqDgXhsMQ

**Comment by maksimKorzh** [comment]
Done.
Btw, check up the new version - it's about 200 Elo stronger

**Comment by fsmosca** [comment]
Looks like this issue is now fixed.
