### ISSUE TITLE
Change version number to 1.1

### ISSUE THREAD

**Issue by fsmosca** [maksimKorzh/wukongJS#4]
[Change to 1.1](https://github.com/maksimKorzh/wukongJS/blob/6434caac9430f593acd694c12333980af5b81556/wukong.js#L26)

**Comment by maksimKorzh** [comment]
Will do soon.
I'm just fighting some search bugs now)

**Comment by maksimKorzh** [comment]
Just fixed the version, but you've already closed the issue)
