### ISSUE TITLE
UCI move list/board state

### ISSUE THREAD

**Issue by o-k-a-y** [maksimKorzh/wukongJS#6]
You said you're using chessjs for the frontend but how does python-chess keep track of the board state? Are you just passing that to the backend?

**Comment by maksimKorzh** [comment]
Here's a tutorial series on this project:
https://www.youtube.com/watch?v=_0uKZbHWVKM&list=PLmN0neTso3Jz-6--Mj51Hc3jiLhkQm0DB

**Comment by o-k-a-y** [comment]
Nice, so you're passing the fen from chessjs to the make_move endpoint then? For some reason I don't see that network request coming up in the browser.

**Comment by maksimKorzh** [comment]
Just navigate to https://maksimkorzh.pythonanywhere.com/
Open devtools => networking
Make move on board => you'll see https://maksimkorzh.pythonanywhere.com/make_move status: 200 etc...
And if you click on this request, here'e the response from API:
{"best_move":"e6","score":"book move"}
