### ISSUE TITLE
Black won't move given a fen string with black to move

### ISSUE THREAD

**Issue by o-k-a-y** [maksimKorzh/wukongJS#8]
1. Give a valid fen string with black to move i.e. rnbqkbnr/pp1ppppp/8/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2 
2. Black won't move and white can't move

**Comment by maksimKorzh** [comment]
1. Navigate to https://maksimkorzh.github.io/wukongJS/wukong.html
2. Paste your FEN => click FEN button => click Move button => black would make a move
3. If you want to play this position from black's perspective do:
Paste your FEN => click FEN button => click Flip button (now you're black) => make move on board (engine would response)

**Comment by o-k-a-y** [comment]
Got it, thanks.

Maybe for usability it would make sense for black to automatically make a move given a FEN with black to move since that is the default behavior for a move when white moves.

**Comment by maksimKorzh** [comment]
This is a demo app.
I prefer "development mode" when you can control everything manually.
Btw if you open console and play you'll see the UCI output regarding score, depth and PV

**Comment by JavlonMardonov** [comment]
> This is a demo app. I prefer "development mode" when you can control everything manually. Btw if you open console and play you'll see the UCI output regarding score, depth and PV

I think, have problem in web gui!, because, when engine thinking time possible to move opponent's pieces by user, I think, is need to repair that !
